export default {
    "data": {
        "code": 200,
        "status": true,
        "data": {
            "current_page": 1,
            "data": [
                {
                    "id": 1841,
                    "user_id": 10,
                    "brand_id": 4,
                    "model_id": 50,
                    "type": 2,
                    "car_case": 2,
                    "current_price": "32423432",
                    "damage_pieces": 5,
                    "damage_pieces_price": "1900.00",
                    "made_year": 2013,
                    "car_desc": "لل",
                    "years_prices": "13030264.28",
                    "kilos": 2343,
                    "kilos_price": "162878.30349863",
                    "final_price": "11827936.152392",
                    "file": null,
                    "reply": null,
                    "created_at": "2024-10-16T06:09:08.000000Z",
                    "updated_at": "2024-10-16T06:11:12.000000Z",
                    "coupon": null,
                    "gearbox": "0",
                    "motor": "1",
                    "city": {
                        "id": 1,
                        "name_en": "Riyadh",
                        "name_ar": "الرياض",
                        "region_id": 2,
                        "created_at": "2024-09-14T11:33:16.000000Z",
                        "updated_at": "2024-09-14T11:33:16.000000Z"
                    },
                    "purpose": 2,
                    "payment_status": "success",
                    "order_details": null,
                    "user": {
                        "id": 10,
                        "name": null,
                        "phone": "+1 (535) 616-8708",
                        "type": "2",
                        "status": null,
                        "lang": null,
                        "image": null,
                        "email": "shtya54@gmail.com",
                        "email_verified_at": null,
                        "created_at": "2024-08-27T09:25:47.000000Z",
                        "updated_at": "2024-10-08T04:11:39.000000Z"
                    },
                    "car_model": {
                        "id": 50,
                        "name_ar": null,
                        "name_en": "Bayanihan H5",
                        "brand_id": 4,
                        "damage_pieces_price": "380",
                        "year_made": null,
                        "years_price": "22-8-8-9-8-7-6-6-5-4-2-1-0",
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-09-10T16:44:00.000000Z",
                        "motor": "0.032",
                        "gearbox": "0.025",
                        "year_percentage": null
                    },
                    "brand": {
                        "id": 4,
                        "title_ar": "بايك",
                        "title_en": "BAIC",
                        "status": 1,
                        "image": null,
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-10-01T10:03:37.000000Z"
                    }
                },
                {
                    "id": 1840,
                    "user_id": 10,
                    "brand_id": 1,
                    "model_id": 3,
                    "type": 1,
                    "car_case": 1,
                    "current_price": "1222132",
                    "damage_pieces": 2,
                    "damage_pieces_price": "3600.00",
                    "made_year": 2022,
                    "car_desc": "يسبي",
                    "years_prices": "836524.91",
                    "kilos": 123,
                    "kilos_price": "10456.561392",
                    "final_price": "791915.049968",
                    "file": null,
                    "reply": null,
                    "created_at": "2024-10-16T06:09:08.000000Z",
                    "updated_at": "2024-10-16T06:11:12.000000Z",
                    "coupon": null,
                    "gearbox": "1",
                    "motor": "0",
                    "city": {
                        "id": 1,
                        "name_en": "Riyadh",
                        "name_ar": "الرياض",
                        "region_id": 2,
                        "created_at": "2024-09-14T11:33:16.000000Z",
                        "updated_at": "2024-09-14T11:33:16.000000Z"
                    },
                    "purpose": 2,
                    "payment_status": "success",
                    "order_details": null,
                    "user": {
                        "id": 10,
                        "name": null,
                        "phone": "+1 (535) 616-8708",
                        "type": "2",
                        "status": null,
                        "lang": null,
                        "image": null,
                        "email": "shtya54@gmail.com",
                        "email_verified_at": null,
                        "created_at": "2024-08-27T09:25:47.000000Z",
                        "updated_at": "2024-10-08T04:11:39.000000Z"
                    },
                    "car_model": {
                        "id": 3,
                        "name_ar": null,
                        "name_en": "Cygnet",
                        "brand_id": 1,
                        "damage_pieces_price": "1800",
                        "year_made": null,
                        "years_price": "20-8-7-8-7-7-7-5-5-3-2-1-0",
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-09-10T16:44:00.000000Z",
                        "motor": "0.032",
                        "gearbox": "0.025",
                        "year_percentage": null
                    },
                    "brand": {
                        "id": 1,
                        "title_ar": "اوستن مارتن",
                        "title_en": "Aston Martin",
                        "status": 1,
                        "image": null,
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-10-01T10:03:37.000000Z"
                    }
                },
                {
                    "id": 1839,
                    "user_id": 10,
                    "brand_id": 4,
                    "model_id": 50,
                    "type": 2,
                    "car_case": 2,
                    "current_price": "32423432",
                    "damage_pieces": 5,
                    "damage_pieces_price": "1900.00",
                    "made_year": 2013,
                    "car_desc": "لل",
                    "years_prices": "13030264.28",
                    "kilos": 2343,
                    "kilos_price": "162878.30349863",
                    "final_price": "11827936.152392",
                    "file": null,
                    "reply": null,
                    "created_at": "2024-10-16T06:00:31.000000Z",
                    "updated_at": "2024-10-16T06:05:32.000000Z",
                    "coupon": null,
                    "gearbox": "0",
                    "motor": "1",
                    "city": {
                        "id": 1,
                        "name_en": "Riyadh",
                        "name_ar": "الرياض",
                        "region_id": 2,
                        "created_at": "2024-09-14T11:33:16.000000Z",
                        "updated_at": "2024-09-14T11:33:16.000000Z"
                    },
                    "purpose": 2,
                    "payment_status": "success",
                    "order_details": null,
                    "user": {
                        "id": 10,
                        "name": null,
                        "phone": "+1 (535) 616-8708",
                        "type": "2",
                        "status": null,
                        "lang": null,
                        "image": null,
                        "email": "shtya54@gmail.com",
                        "email_verified_at": null,
                        "created_at": "2024-08-27T09:25:47.000000Z",
                        "updated_at": "2024-10-08T04:11:39.000000Z"
                    },
                    "car_model": {
                        "id": 50,
                        "name_ar": null,
                        "name_en": "Bayanihan H5",
                        "brand_id": 4,
                        "damage_pieces_price": "380",
                        "year_made": null,
                        "years_price": "22-8-8-9-8-7-6-6-5-4-2-1-0",
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-09-10T16:44:00.000000Z",
                        "motor": "0.032",
                        "gearbox": "0.025",
                        "year_percentage": null
                    },
                    "brand": {
                        "id": 4,
                        "title_ar": "بايك",
                        "title_en": "BAIC",
                        "status": 1,
                        "image": null,
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-10-01T10:03:37.000000Z"
                    }
                },
                {
                    "id": 1838,
                    "user_id": 10,
                    "brand_id": 1,
                    "model_id": 3,
                    "type": 1,
                    "car_case": 1,
                    "current_price": "1222132",
                    "damage_pieces": 2,
                    "damage_pieces_price": "3600.00",
                    "made_year": 2022,
                    "car_desc": "يسبي",
                    "years_prices": "836524.91",
                    "kilos": 123,
                    "kilos_price": "10456.561392",
                    "final_price": "791915.049968",
                    "file": null,
                    "reply": null,
                    "created_at": "2024-10-16T06:00:31.000000Z",
                    "updated_at": "2024-10-16T06:05:32.000000Z",
                    "coupon": null,
                    "gearbox": "1",
                    "motor": "0",
                    "city": {
                        "id": 1,
                        "name_en": "Riyadh",
                        "name_ar": "الرياض",
                        "region_id": 2,
                        "created_at": "2024-09-14T11:33:16.000000Z",
                        "updated_at": "2024-09-14T11:33:16.000000Z"
                    },
                    "purpose": 2,
                    "payment_status": "success",
                    "order_details": null,
                    "user": {
                        "id": 10,
                        "name": null,
                        "phone": "+1 (535) 616-8708",
                        "type": "2",
                        "status": null,
                        "lang": null,
                        "image": null,
                        "email": "shtya54@gmail.com",
                        "email_verified_at": null,
                        "created_at": "2024-08-27T09:25:47.000000Z",
                        "updated_at": "2024-10-08T04:11:39.000000Z"
                    },
                    "car_model": {
                        "id": 3,
                        "name_ar": null,
                        "name_en": "Cygnet",
                        "brand_id": 1,
                        "damage_pieces_price": "1800",
                        "year_made": null,
                        "years_price": "20-8-7-8-7-7-7-5-5-3-2-1-0",
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-09-10T16:44:00.000000Z",
                        "motor": "0.032",
                        "gearbox": "0.025",
                        "year_percentage": null
                    },
                    "brand": {
                        "id": 1,
                        "title_ar": "اوستن مارتن",
                        "title_en": "Aston Martin",
                        "status": 1,
                        "image": null,
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-10-01T10:03:37.000000Z"
                    }
                },
                {
                    "id": 1841,
                    "user_id": 10,
                    "brand_id": 4,
                    "model_id": 50,
                    "type": 2,
                    "car_case": 2,
                    "current_price": "32423432",
                    "damage_pieces": 5,
                    "damage_pieces_price": "1900.00",
                    "made_year": 2013,
                    "car_desc": "لل",
                    "years_prices": "13030264.28",
                    "kilos": 2343,
                    "kilos_price": "162878.30349863",
                    "final_price": "11827936.152392",
                    "file": null,
                    "reply": null,
                    "created_at": "2024-10-16T06:09:08.000000Z",
                    "updated_at": "2024-10-16T06:11:12.000000Z",
                    "coupon": null,
                    "gearbox": "0",
                    "motor": "1",
                    "city": {
                        "id": 1,
                        "name_en": "Riyadh",
                        "name_ar": "الرياض",
                        "region_id": 2,
                        "created_at": "2024-09-14T11:33:16.000000Z",
                        "updated_at": "2024-09-14T11:33:16.000000Z"
                    },
                    "purpose": 2,
                    "payment_status": "success",
                    "order_details": null,
                    "user": {
                        "id": 10,
                        "name": null,
                        "phone": "+1 (535) 616-8708",
                        "type": "2",
                        "status": null,
                        "lang": null,
                        "image": null,
                        "email": "shtya54@gmail.com",
                        "email_verified_at": null,
                        "created_at": "2024-08-27T09:25:47.000000Z",
                        "updated_at": "2024-10-08T04:11:39.000000Z"
                    },
                    "car_model": {
                        "id": 50,
                        "name_ar": null,
                        "name_en": "Bayanihan H5",
                        "brand_id": 4,
                        "damage_pieces_price": "380",
                        "year_made": null,
                        "years_price": "22-8-8-9-8-7-6-6-5-4-2-1-0",
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-09-10T16:44:00.000000Z",
                        "motor": "0.032",
                        "gearbox": "0.025",
                        "year_percentage": null
                    },
                    "brand": {
                        "id": 4,
                        "title_ar": "بايك",
                        "title_en": "BAIC",
                        "status": 1,
                        "image": null,
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-10-01T10:03:37.000000Z"
                    }
                },
                {
                    "id": 1840,
                    "user_id": 10,
                    "brand_id": 1,
                    "model_id": 3,
                    "type": 1,
                    "car_case": 1,
                    "current_price": "1222132",
                    "damage_pieces": 2,
                    "damage_pieces_price": "3600.00",
                    "made_year": 2022,
                    "car_desc": "يسبي",
                    "years_prices": "836524.91",
                    "kilos": 123,
                    "kilos_price": "10456.561392",
                    "final_price": "791915.049968",
                    "file": null,
                    "reply": null,
                    "created_at": "2024-10-16T06:09:08.000000Z",
                    "updated_at": "2024-10-16T06:11:12.000000Z",
                    "coupon": null,
                    "gearbox": "1",
                    "motor": "0",
                    "city": {
                        "id": 1,
                        "name_en": "Riyadh",
                        "name_ar": "الرياض",
                        "region_id": 2,
                        "created_at": "2024-09-14T11:33:16.000000Z",
                        "updated_at": "2024-09-14T11:33:16.000000Z"
                    },
                    "purpose": 2,
                    "payment_status": "success",
                    "order_details": null,
                    "user": {
                        "id": 10,
                        "name": null,
                        "phone": "+1 (535) 616-8708",
                        "type": "2",
                        "status": null,
                        "lang": null,
                        "image": null,
                        "email": "shtya54@gmail.com",
                        "email_verified_at": null,
                        "created_at": "2024-08-27T09:25:47.000000Z",
                        "updated_at": "2024-10-08T04:11:39.000000Z"
                    },
                    "car_model": {
                        "id": 3,
                        "name_ar": null,
                        "name_en": "Cygnet",
                        "brand_id": 1,
                        "damage_pieces_price": "1800",
                        "year_made": null,
                        "years_price": "20-8-7-8-7-7-7-5-5-3-2-1-0",
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-09-10T16:44:00.000000Z",
                        "motor": "0.032",
                        "gearbox": "0.025",
                        "year_percentage": null
                    },
                    "brand": {
                        "id": 1,
                        "title_ar": "اوستن مارتن",
                        "title_en": "Aston Martin",
                        "status": 1,
                        "image": null,
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-10-01T10:03:37.000000Z"
                    }
                },
                {
                    "id": 1839,
                    "user_id": 10,
                    "brand_id": 4,
                    "model_id": 50,
                    "type": 2,
                    "car_case": 2,
                    "current_price": "32423432",
                    "damage_pieces": 5,
                    "damage_pieces_price": "1900.00",
                    "made_year": 2013,
                    "car_desc": "لل",
                    "years_prices": "13030264.28",
                    "kilos": 2343,
                    "kilos_price": "162878.30349863",
                    "final_price": "11827936.152392",
                    "file": null,
                    "reply": null,
                    "created_at": "2024-10-16T06:00:31.000000Z",
                    "updated_at": "2024-10-16T06:05:32.000000Z",
                    "coupon": null,
                    "gearbox": "0",
                    "motor": "1",
                    "city": {
                        "id": 1,
                        "name_en": "Riyadh",
                        "name_ar": "الرياض",
                        "region_id": 2,
                        "created_at": "2024-09-14T11:33:16.000000Z",
                        "updated_at": "2024-09-14T11:33:16.000000Z"
                    },
                    "purpose": 2,
                    "payment_status": "success",
                    "order_details": null,
                    "user": {
                        "id": 10,
                        "name": null,
                        "phone": "+1 (535) 616-8708",
                        "type": "2",
                        "status": null,
                        "lang": null,
                        "image": null,
                        "email": "shtya54@gmail.com",
                        "email_verified_at": null,
                        "created_at": "2024-08-27T09:25:47.000000Z",
                        "updated_at": "2024-10-08T04:11:39.000000Z"
                    },
                    "car_model": {
                        "id": 50,
                        "name_ar": null,
                        "name_en": "Bayanihan H5",
                        "brand_id": 4,
                        "damage_pieces_price": "380",
                        "year_made": null,
                        "years_price": "22-8-8-9-8-7-6-6-5-4-2-1-0",
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-09-10T16:44:00.000000Z",
                        "motor": "0.032",
                        "gearbox": "0.025",
                        "year_percentage": null
                    },
                    "brand": {
                        "id": 4,
                        "title_ar": "بايك",
                        "title_en": "BAIC",
                        "status": 1,
                        "image": null,
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-10-01T10:03:37.000000Z"
                    }
                },
                {
                    "id": 1838,
                    "user_id": 10,
                    "brand_id": 1,
                    "model_id": 3,
                    "type": 1,
                    "car_case": 1,
                    "current_price": "1222132",
                    "damage_pieces": 2,
                    "damage_pieces_price": "3600.00",
                    "made_year": 2022,
                    "car_desc": "يسبي",
                    "years_prices": "836524.91",
                    "kilos": 123,
                    "kilos_price": "10456.561392",
                    "final_price": "791915.049968",
                    "file": null,
                    "reply": null,
                    "created_at": "2024-10-16T06:00:31.000000Z",
                    "updated_at": "2024-10-16T06:05:32.000000Z",
                    "coupon": null,
                    "gearbox": "1",
                    "motor": "0",
                    "city": {
                        "id": 1,
                        "name_en": "Riyadh",
                        "name_ar": "الرياض",
                        "region_id": 2,
                        "created_at": "2024-09-14T11:33:16.000000Z",
                        "updated_at": "2024-09-14T11:33:16.000000Z"
                    },
                    "purpose": 2,
                    "payment_status": "success",
                    "order_details": null,
                    "user": {
                        "id": 10,
                        "name": null,
                        "phone": "+1 (535) 616-8708",
                        "type": "2",
                        "status": null,
                        "lang": null,
                        "image": null,
                        "email": "shtya54@gmail.com",
                        "email_verified_at": null,
                        "created_at": "2024-08-27T09:25:47.000000Z",
                        "updated_at": "2024-10-08T04:11:39.000000Z"
                    },
                    "car_model": {
                        "id": 3,
                        "name_ar": null,
                        "name_en": "Cygnet",
                        "brand_id": 1,
                        "damage_pieces_price": "1800",
                        "year_made": null,
                        "years_price": "20-8-7-8-7-7-7-5-5-3-2-1-0",
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-09-10T16:44:00.000000Z",
                        "motor": "0.032",
                        "gearbox": "0.025",
                        "year_percentage": null
                    },
                    "brand": {
                        "id": 1,
                        "title_ar": "اوستن مارتن",
                        "title_en": "Aston Martin",
                        "status": 1,
                        "image": null,
                        "created_at": "2024-09-10T16:44:00.000000Z",
                        "updated_at": "2024-10-01T10:03:37.000000Z"
                    }
                },
            ],
            "first_page_url": "https://api.soomha.net/api/user/order/user/10?page=1",
            "from": 1,
            "last_page": 12,
            "last_page_url": "https://api.soomha.net/api/user/order/user/10?page=1",
            "links": [
                {
                    "url": null,
                    "label": "&laquo; Previous",
                    "active": false
                },
                {
                    "url": "https://api.soomha.net/api/user/order/user/10?page=1",
                    "label": "1",
                    "active": true
                },
                {
                    "url": null,
                    "label": "Next &raquo;",
                    "active": false
                }
            ],
            "next_page_url": null,
            "path": "https://api.soomha.net/api/user/order/user/10",
            "per_page": 10,
            "prev_page_url": null,
            "to": 4,
            "total": 4
        },
        "message": "  جميع  الطلبات"
    },
    "status": 200,
    "statusText": "OK",
    "headers": {
        "cache-control": "no-cache, private",
        "content-type": "application/json"
    },
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http",
            "fetch"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Authorization": "Bearer 601|MNGloGC7CVDf4tD4m1eySxoKzBmMCIVrPXP6048l29fcbc55",
            "Accept-Language": "en"
        },
        "baseURL": "https://api.soomha.net/api",
        "method": "get",
        "url": "/user/order/user/10"
    },
    "request": {}
}